version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=swejal
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432